
[[sec-overview]]
== Overview

=== Preface

The “Data Classification and Encoding Guide” has been developed to provide consistent, standardized instructions for encoding S-412 data.

The purpose of the Data Classification and Encoding Guide is to facilitate S-412 encoding to meet WMO SERCOM standards for the proper display of Marine Weather Warning information in an ECDIS. The document describes how to encode marine weather information considered relevant to be displayed on an ECDIS. 

The content of a Marine Weather Warning product is at the discretion of the producing authority, provided that the conventions described within this document are followed. A “producing authority” is a Hydrographic Office (HO) or an organization authorized by a government, HO or other relevant government institution to produce Marine Weather Warning product.

=== S-412 Annex A — Data Classification and Encoding Guide — Metadata

NOTE  This information uniquely identifies this Annex to the Product Specification and provides information about its creation and maintenance.

*Title*::  The World Meteorological Organization Marine Weather Warning Product Specification, Annex A – Data Classification and Encoding Guide
*Version*::  1.2.0
*Date*:: January 2026
*Language*::  English
*Classification*::  Unclassified
*Contact*::  World Meteorological Organization +
7 bis, avenue de la Paix +
P.O. Box 2300 +
CH-1211 Geneva 2, Switzerland +
Telephone: +41 (0) 22 730 84 03 +
Email: publications@wmo.int +
*URL*::  https://mwo.int/[www.wmo.int] +
*Identifier*::  S-412 Annex A +
*Maintenance*::  Changes to S-412 Annex A; Data Classification and Encoding Guide are coordinated by the SERCOM, formely JCOMM and must be made available via the IHO web site.

=== Terms, definitions and abbreviations

==== Terms and definition

See S-412 Product Specification main document, clause 1.4.

==== Abbreviated terms

For a list of abbreviations, see S-412 Product Specification main document, Clause 1.6.1.

=== Use of language
Within this document:
• “Must” indicates a mandatory requirement. +
• “Should” indicates an optional requirement, that is the recommended process to be followed, but is
not mandatory. +
• “May” means “allowed to” or “could possibly” and is not mandatory.


=== Maintenance
Changes to the Data Classification and Encoding Guide must occur in accordance with the S-412 Marine Weather Warning Product Specification clause 1.9.


