
[[sec-overview-2]]
== General

=== Introduction

This S-412 Data Classification and Encoding Guide (DCEG) contains rules and guidance for converting data describing the real world into data products that conform to the S-412 specification.

The S-412 specification contains an application schema (UML model) describing the conceptual domain model in terms of classes and a Feature Catalogue that specifies the data model, i.e., specifies the data model types corresponding to the various classes in the application schema.

To simplify the DCEG text, the various data model types will be provided without the suffixes “class”, “type” or “instance”; e.g. the term “feature” should be understood as “feature class” or “feature type” or “feature instance” as best fits the immediate context in which it is used (and where there might be confusion, it is written out in full as feature class/type/instance). The model defines real world entities as a combination of descriptive and spatial characteristics (S-412 Product Specification - section 4).

This clause of the DCEG contains general information needed to understand the encoding rules and describes fundamental common rules and constraints. It also describes datasets and metadata. The data model object types used within S-412 and their encoding rules and guidelines are defined in detail in subsequent clauses of this document.

Within this document the features and attributes appear in bold text or italic text, to distinguish them from surrounding words.

=== Multiple Datasets

In order to facilitate the efficient processing and exchange of S-412 data, S-412 data files will be split by the time and date in which the file data is valid.

_Guidance to be enhanced by WMO._

=== Descriptive characteristics

==== Feature

A feature contains descriptive attributes that characterize real world entities.

The word ‘feature’ as used in the ISO 191xx series and in S-100 based product specifications has two distinct but related senses – ‘feature type’ and ‘feature instance’. A feature instance is a single occurrence of the feature and is represented as an object in a dataset.

The location of a feature instance on the Earth’s surface is indicated by a relationship to one or more spatial primitive instances.

S-412 makes use of the Geographic (Geo) feature type which carries the descriptive characteristics of a real-world entity and of the Information type feature which carries information associated to one or more geo feature.

==== Attributes

===== Simple attribute types
Each simple attribute in S-100 is assigned to one of 9 types. In the tables within this document the abbreviation is listed to identify the attribute type:

* Enumeration (EN): A fixed list of valid identifiers of named literal values. Attributes of an enumerated type may only take values from this list. The complete list of allowable values for S-101 enumeration type attributes is included in Sections 27, 28 and 30; these values may be further constrained for the binding of the attribute to specific feature and information types.
* Boolean (BO): A value representing binary logic. The value can be either True or False.
* Real (RE): A signed Real (floating point) number consisting of a mantissa and an exponent. The representation of a real is encapsulation and usage dependent.
* Integer (IN): A signed integer number. The representation of an integer is encapsulation and usage dependent.
* Text (TE): A CharacterString, that is an arbitrary-length sequence of characters including accents and special characters from a repertoire of one of the adopted character sets.
* Truncated Date (TD) : Allows a partial date to be encoded as an extension to the ISO 8601 compliant date attribute type values for year, month and day according to the Gregorian Calendar. Character encoding of a date is a string which follows the calendar date format (complete representation, basic format) for date specified by ISO 8601.
* Time (TI) : A time is given by an hour, minute and second in the 24-hour clock system. Character encoding of a time shall be a complete representation of the basic format as defined in ISO 8601. Complete representation means that hours, minutes and seconds shall be used. Basic format means that separating characters are omitted.
* Universal Resource Identifier  (URI): A derivation of CharacterString. URI is a uniform resource identifier as defined in RFC 3986. Character encoding of a URI must follow the syntax rules defined in RFC 3986.
* Universal Resource Name (URN): A derivation of the CharacterString predefined derived type Universal Resource Identifier (URI). URN allows a persistent, location-independent, resource identifier to be encoded that follows the syntax and semantics for URNs specified in RFC 2141.


==== Geographic feature class

Geographic (Geo) feature types carry the descriptive characteristics of a real world entity which is provided by a spatial primitive instance.

==== Meta feature class

S-412 does not make use of meta features.

==== Charted background feature

The data product is primarily distributed to be visualized as an overlay of an S-101 ENC on an ECDIS or other GIS applications. Consequently, all necessary descriptive and spatial characteristics to provide a charted background should be provided by the underlying application.

=== Spatial characteristics

==== Spatial primitives

The allowable geometric primitive for each feature type is defined in the Feature Catalogue. The only allowable geometric primitive in an S-412 data product is surface. 

Each spatial value must be referenced by at least one feature instance.

==== Time

S-412 datasets can represent real-world phenomena in the present or future. Because of the unique nature of atmospheric and oceanographic concepts and their geographical changes in time, a variety of time attributes are included in S-412 to ensure instances of features are attributed correctly through time. Features or information types outside of the temporal range of a dataset shall not be included in a dataset. Time shall always be provided in Coordinated Universal Time (UTC).

The fixedDateRange is a complex attribute consisting of simple attributes, dateTimeStart and dateTimeEnd, to allow certain features to define a specific temporal range. The fixedDateRange attribute is mandatory for each feature. This attribute provides data producers the flexibility to manage the temporal resolution of their datasets at the feature level and to concatenate data files in a manner which best suits their workflow and customer’s needs. In order for features to be portrayed, the user’s system must clearly indicate the fixedDateRange of a feature or a group of features if the values are the same. Instances of this attribute may be used for data validation and to ensure temporal quality.

Three other simple dateTime attributes (issuedDateTime, nextUpdateDateTime, and cancellationDate) are mandatory for each WeatherWarning and inherited into the sub-feature types. The issuedDateTime attribute provides a timestamp for when the WeatherWarning has been issued. The nextUpdateDateTime attribute provides the time information for the next expected WeatherWarning to be issued. The cancellationDate is used to mark when a WeatherWarning is set to expire, or be cancelled.

//TODO Fix Figure
// Every time attribute is associated with the abstract WeatherWarning feature type. These attributes are then inherited by all sub-types of WeatherWarning (windWarning, significantWaveHeightWarning, iceAccretionWarning, restrictedVisibilityWarning, and thunderstormWarning). This is shown in <<fig-time-attributes-associated-with-weather-warning>>.

