
[[sec-overview]]
== Overview
=== Introduction
This document has been produced by the National Oceanic and Atmospheric Administration (NOAA) National Weather Service (NWS) Ocean Prediction Center (OPC) on behalf of the Joint World Meteorological Organization – Intergovernmental Oceanographic Commission (WMO-IOC) Technical Commission for Oceanography and Marine Meteorology (JCOMM), now WMO Commission for Weather, Climate, Hydrological, Marine, and Related Environmental Services and Applications (SERCOM), and the Worldwide Met-Ocean Information and Warning Service (WWMIWS) to define a data product that can be used as a Nautical Publication Information Overlay (NPIO) within electronic charting systems (ECS), including Electronic Chart Display and Information Systems (ECDIS). It has been developed within the framework specification defined by the International Hydrographic Organization (IHO) S-100 Universal Hydrographic Data Model and the International Standards Organization (ISO) 19100 series of standards. This product specification, S-412, is primarily intended for encoding maritime weather and wave warnings. These warnings include polygon portrayals of different hazardous weather conditions forecasted during the warning period to enhance situational awareness, route planning, and route monitoring.

=== Information
This product specification, S-412, is a vector graphic product specification that is primarily intended for encoding information on meteorological and oceanographic warnings that are used by mariners for route-planning, hazard avoidance, and risk mitigation. S-412 defines meteorological and oceanographic features, attributes, and relationships, as well as their mapping to a dataset.

=== Scope
This document is maintained by the World Meteorological Organization (WMO) and describes an IHO S-100 compliant product specification for meteorological and oceanographic datasets, which will primarily act as an overlay for S-101 Electronic Navigational Charts on an S-100 based ECS, including ECDIS, in order to provide the maritime community with greater situational awareness. It specifies the content, structure, and metadata needed for creating a fully compliant Marine Weather Warnings dataset that will be compatible with an S-100 capable electronic navigation system. This product specification includes the content model, encoding guides, feature catalogue, portrayal catalogue, metadata, and example datasets.

In addition to acting as an overlay for S-101 Electronic Navigation Charts, this product specification outlines the capacity to interoperate with other S-100 compliant product specifications in accordance with the IHO S-98 Interoperability Specification.

This product specification does not include recommended changes to or requirements for services by National Meteorological Services.

[bibliography]
=== References

==== Normative References
* NOAA National Weather Service Glossary (https://forecast.weather.gov/glossary.php)

* National Weather Service Instruction 10-315, Marine Weather Message, 2020 Edition

* National Weather Service Instruction 10-303, Marine and Coastal Services Standards and Guidelines, 2022 Edition

* National Weather Service Instruction 10-604, Tropical Cyclone Names and Definitions, 2021 Edition

* National Weather Service Instruction 10-811, Enroute Forecasts and Advisories, 2022 Edition

* National Weather Service Policy Directive 10-6, Tropical Cyclone Weather Services Program, 2020 Edition

* S-32, IHO Hydrographic Dictionary, 2023 Edition

* S-53 Joint IHO/IMO/WMO Manual on Maritime Safety Information (MSI), January 2016 Edition

* S-98 Interoperability Specification, 2022 Edition

* S-100 IHO Universal Hydrographic Data Model, 2024 Edition

* S-101 IHO Electronic Navigation Chart Product Specification, 2024 Edition

* WMO 8 Guide to Meteorological Instruments and Methods of Observation, 2023 Edition

* WMO 182 International Meteorological Vocabulary, 1992 Edition

* WMO 306 Manual on Codes, 2024 Edition

* WMO 386 Manual on the Global Telecommunication System, 2020 Edition

* WMO 471 Guide to Marine Meteorological Services, 2024 Edition

* WMO 485 Manual on the Global Data-processing and Forecasting System, 2023 Edition

* WMO 558 Manual on Marine Meteorological Services, 2024 Edition

* WMO 702 Guide to Wave Analysis and Forecasting, 2020 Edition

* WMO/TD 850, 1998 Edition

* Global Maritime Distress and Safety System, GMDSS (weather.gov)

* IHO Geospatial Information Registry

* ISO 8601. 2004. Data elements and interchange formats – Information interchange – Representation of dates and times. 2004.

* ISO 3166-1. 2020. Country Codes. 2020.

* ISO 639-2/T. 1998. Language Codes. 1998.

* ISO/TS 19103. 2024. Geographic information – Conceptual schema language. 2024.

* ISO 19111. 2019. Geographic Information – Spatial referencing by coordinates. 2019.

* ISO 19115. 2003. Geographic Information – Metadata. 2003.

* ISO 19115-1. 2014. Geographic information - Metadata - Part 1: Fundamentals. 2014

* ISO 19115-2.2019. Geographic Information – Metadata – Part 2: Extension for imagery and gridded data. 2019.

* ISO/TS 19123. 2005. Geographic information – Schema for coverage geometry and functions. 2005.

* ISO/TS 19123-1. 2023. Geographic information – Schema for coverage geometry and functions. Part 1: Fundamentals. 2023.

* ISO 19129. 2009. Geographic information – Imagery, gridded and coverage data framework. 2009.

* ISO 19131. 2022. Geographic information – Data product specifications. 2022.

* ISO 19136:2007. Geographic Information – Geographic Markup Language (GML). 2007.

* ISO 19136-1:2020. Geographic Information – Geographic Markup Language (GML). Part 1: Fundamentals. 2020.

* ISO/IEC 19501. 2005. Information technology – Unified Modeling Language (UML) Version 1.4.2. 2005

==== Informative References
* IMO A27/Res. 1051, IMO/WMO Worldwide Met-Ocean Information and Warning Service, 2011 Edition

* ISO 19101:2002. Geographic information – Reference model. 2002.

* ISO 19101-1:2014. Geographic information – Reference model. Part 1: Fundamentals. 2014.

* ISO 19103: 2024. Geographic information – Conceptual schema language – 2024.

* ISO 19105: 2022. Geographic information – Conformance and testing. 2022.

* ISO 19107:2019. Geographic information – Spatial schema. 2019.

* ISO 19108:2002. Geographic information – Temporal schema. 2002.

* ISO 19109:2015. Geographic information – Rules for application schema. 2015.

* ISO 19110: 2016. Geographic information – Methodology for feature cataloguing. 2016.

* ISO 19113: 2005. Geographic information – Quality principles. 2005

* ISO 19116: 2019. Geographic information – Positioning services. 2019.

* ISO 19117:2012. Geographic information – Portrayal. 2012

* ISO 19118: 2011. Geographic information – Encoding. 2011.

* ISO 19128:2005. Geographic information – Web Map Server interface. 2005

* 19132: 2007. Geographic information – Location-based services – Reference model. 2007.

* ISO 19133:2005. Geographic information – Location-based services – Tracking and navigation. 2005.

* ISO 19138:2006. Geographic information – Data quality measures. 2006.

* ISO 19142:2010. Geographic information – Web Feature Service. 2010

* ISO 19144-1:2009. Geographic information – Classification systems – Part 1: Classification system structure. 2009.

* ISO 19145:2013. Geographic information – Registry of representations of geographic point location. 2013.

* ISO 19153:2014. Geographic information – Geospatial Digital Rights Management Reference Model (GeoDRM RM) 1). 2014.

* ISO 19156:2023. Geographic information – Observations and measurements. 2011.

* ISO 19157:2023. Geographic information – Data quality. 2013.

* ISO/TS 19158:2012. Geographic information – Quality assurance of data supply. 2010.


[bibliography]
=== References
* [[[iho-s100,IHO S-100 5.2.0]]]

* [[[iho-s44,IHO S-44]]]

* [[[iho-s4,IHO S-4]]]

* [[[iho-s32,IHO S-32]]]

* [[[iso-8601,ISO 8601:2004]]]

* [[[iso-19103,ISO 19103:2015]]]

* [[[iso-19111,ISO 19111:2007]]]

* [[[iso-19115-1,ISO 19115-1:2014/Amd 1:2018]]]

* [[[iso-19115-2,ISO 19115-2:2009]]]

* [[[iso-19115-3,ISO/TS 19115-3:2016]]]


==== Normative
GML OpenGIS®:: _Geography Markup Language (GML) Encoding Standard_ (Version 3.2.1)
S-97:: _IHO Guidelines for Creating S-100 Product Specifications_, Edition 1.1.0, June 2020.
S-100:: _IHO Universal Hydrographic Data Model_, Edition 5.2.0, June 2024

==== Informative
ISO 19101:: _Geographic Information – Reference Model_, 2003
ISO 19103:: _Geographic Information – Conceptual Schema Language_, 2005
ISO 19103-2:: _Geographic Information – Conceptual Schema Language – Part 2_, 2005
ISO 19109:: _Geographic Information – Rules for Application Schema_, 2005
ISO 19110:: _Geographic Information – Methodology for Feature Cataloguing_, 2005
ISO 19111:: _Geographic Information – Spatial Referencing by Coordinates_, 2007
ISO 19115-1:: _Geographic information - Metadata - Part 1: Fundamentals_ - 2014/Amd 1: 2018
ISO 19115-3:: _Geographic information - Metadata - Part 3: XML Schema implementation for fundamental concepts_ - 2016
ISO 19117:: _Geographic Information – Portrayal_, 2012
ISO 19131:: _Geographic Information – Data Product Specifications_, 2008
ISO 19139-1:: _Geographic information - XML schema implementation - Part 1: Encoding rules_ - 2019

=== Terms, definitions and abbreviations

==== Use of language

Within this document:

* "`Must`" indicates a mandatory requirement.
* "`Should`" indicates an optional requirement, that is the recommended process to be followed, but is not mandatory.
* "`May`" means "`allowed to`" or "`could possibly`" and is not mandatory.


==== Terms and definitions
The S-100 framework is based on the ISO 19100 series of geographic standards. The terms and definitions provided here are used to standardise the relevant nomenclature found within that framework, whenever possible. Additional definitions specific to S-412 are provided in this section as well. Features, attributes and associations that may be realised in an S-412 compliant dataset are defined in Annex A, B and C.

*Abstract Class*
An object class which cannot be instantiated, or is designated in an information model as not allowed  to be instantiated [ISO 19107].

NOTE:: subclasses of an abstract class may be either abstract or non-abstract.

*Aggregation*

Special form of association that specifies a whole-part relationship between the aggregate (whole)  and a component part (see composition) [ISO 19103] 

*Application*

Manipulation and processing of data in support of user requirements [ISO 19101-1:2014]

*Application Schema*

Conceptual schema for data required by one or more applications [ISO 19101].

*Association*

Semantic relationship between two or more classifiers that specifies connections among their instances [ISO 19101].

NOTE:: a binary association is an association among exactly two classifiers (including the possibility of an association from a classifier to itself).

*Attribute*

Named property of an entity [ISO/IEC 2382-17:1999].

NOTE:: Describes a geometrical, thematic, or other characteristic of an entity.

_(2) Feature within a classifier that describes a range of values that instances of the classifier may hold._

_NOTE:: An attribute is semantically equivalent to a composition association; however, the intent and usage is normally different._

_NOTE:: “Feature” used in this definition is the UML meaning of the term._

*_Boundary_*

_Set that represents the limit of an entity._

_NOTE:: Boundary is most commonly used in the context of geometry, where the set is a collection of points or a collection of objects that represent those points._

*Cartesian Coordinate System*

Coordinate system which gives the position of points relative to n mutually perpendicular axes. [ISO 19111]

*Class*

Description of a set of objects that share the same attributes, operations, methods, relationships, and semantics [ISO/TS 19103:2005].

NOTE:: a class represents a concept within the system being modelled. Depending on the kind of model, the concept may be real-world (for an analysis model), or it may also contain algorithmic and computer implementation concepts (for a design model). A classifier is a generalisation of class that includes other class-like elements, such as data type, actor and component.

*Code List*

Value domain including a code for a permissible value [ISO 19136].

*Coordinate*

One of a sequence of _n_ numbers designating the position of a *point* in N-dimensional space [ISO 19111].

NOTE:: In a *coordinate reference system*, the coordinate numbers are qualified by units [ISO 19107, ISO 19111].

*Coordinate Reference System*

A coordinate system that is related to the real world by a datum [ISO 19111].

NOTE:: for geodetic and vertical datums, it will be related to the Earth.

*Coverage*

Feature that acts as a function to return values from its range for any direction position within its spatial, temporal, or spatiotemporal domain [ISO 19123:2005].

Example: Examples include a raster image, polygon overlay, or digital elevation matrix type.

*Coverage Geometry*

Configuration of the domain of a coverage described in terms of coordinates [ISO 19123].

*Curve*

1-dimensional geometric primitive, representing the continuous image of a line[ISO 19107].

NOTE:: The boundary of a curve is the set of points at either end of the curve. If the curve is a cycle, the two ends are identical, and the curve (if topologically closed) is considered to not have a boundary. The first point is called the start point, and the last is the end point. Connectivity of the curve is guaranteed by the "continuous image of a line" clause. A topological theorem states that a continuous image of a connected set is connected.

*Data Product*

A dataset or dataset series that conforms to a data product specification [ISO 19131].

*Data Set*

Identifiable collection of data [ISO 19115].

NOTE:: a dataset may be a smaller grouping of data which, though limited by some constraint such as spatial extent or feature type, is located physically within a larger dataset. Theoretically, a dataset may be as small as a single feature or feature attribute contained within a larger dataset. A hardcopy map or chart may be considered a dataset.

*_Data Quality_*

_A set of elements describing aspects of quality, including a measure of quality, an evaluation procedure, a quality result, and a scope._

*Data Type*

Specification of a value domain with operations allowed on values in this domain [ISO/TS 19103:2005].

Example: Integer, Real, Boolean, String, Date

_NOTE:: Data types include primitive predefined types and user-definable types._

_NOTE:: A data type is identified by a term, for example Integer._

*_Datum_*

_Parameter or set of parameters that define the position of the origin, the scale, and the orientation of a *coordinate* system._

*_ECDIS_*

A navigation information system which with adequate back-up arrangements can be accepted as complying with the up-to-date chart required by regulations V/19 and V/27 of the 1974 SOLAS Convention, as amended, by displaying selected information from a System Electronic Navigational Chart (System Database) with positional information from navigation sensors to assist the Mariner in route planning and route monitoring, and if required display additional navigation-related information.

*_Enumeration_*

_A fixed list of valid identifiers of named literal values. Attributes of an enumerated type may only take values from this list._

*Feature*

Abstraction of real-world phenomena [ISO 19101:2003].

Example: The phenomenon truck may be classified with other similar phenomena into a feature type named automobile.

_NOTE:: A feature may occur as a type or an instance. Feature type or feature instance should be used when only one is meant._

*Feature Attribute*

Characteristic of a *feature* [ISO 19101].

NOTE:: A feature attribute type has a name, a data type, and a domain associated to it. A feature attribute instance has an attribute value taken from the value domain of the feature attribute type.

Example: A feature attribute named ‘colour’ may have an attribute value ‘green’ which belongs to the data type ‘text’.

*Feature Catalogue*

A catalogue containing definitions and descriptions of the *feature* types, *feature attributes* and occurring in one or more sets of geographic data [ISO 19110].

*Geometric Primitive*

Geometric object representing a single, connected, homogeneous element of geometry.

NOTE:: Geometric primitives are non-decomposed objects that present information about geometric configuration. They include points, curves and surfaces.

*Multiplicity*

Specification of the number of possible occurrences of a property, or the number of allowable elements that may participate in a given relationship.

EXAMPLES: 1..* (one to many); 1 (exactly one); 0..1 (zero or one)

*Point*

0-dimensional geometric primitive, representing a position.

NOTE:: The boundary of a point is the empty set.

*Portrayal Catalogue*

Collection of defined portrayals for a feature catalogue.

NOTE:: Content of a portrayal catalogue includes portrayal functions, symbols, and portrayal context.

==== Abbreviations
This Product Specification adopts the following convention for presentation purposes:

BSH:: Bundesamt für Seeschifffahrt und Hydrographie (Germany)
CRS::  Coordinate Reference System
ECDIS:: Electronic Chart Display and Information System
ENC:: Electronic Navigational Chart
EPSG:: European Petroleum Survey Group
GML:: Geography Markup Language
IHO:: International Hydrographic Organization
ISO:: International Organization for Standardization
JCOMM:: Joint Technical Commission for Oceanography and Marine Meteorology
UTF-8:: Unicode Transformation Format-8
WMO:: World Meteorological Organization
XML:: eXtensible Markup Language

=== General data product description

*Title*:: Wind and Weather Warning Product Specification.

*Abstract*:: IWind and Weather Warning

*Acronym*:: S-411

*Content*:: Wind and Weather Warnings as vector data

*Spatial Extent*::

*Description*: Areas specific to navigation. +
*East Bounding Longitude*: 180° +
*West Bounding Longitude*: -180° +
*North Bounding Latitude*: 90° +
*South Bounding Latitude*: -90°

*Purpose*:: Navigation

=== Product Specification metadata

*Title*:: Wind and Weather Warnings Product Specification
*S-100 Version*:: 5.2.0
*S-411 Version*:: 2.0.0
*Date*:: 31 December 2025
*Language*:: English (optional additional)
*Classification*:: Unclassified
*Contact*::
*Identifier*::
*Maintenance*:: Changes to this product specification are coordinated by JCOMM ETSI. +
--
World Meteorological Organization (WMO) +
7 bis, avenue de la Paix +
P.O. Box 2300 +
CH-1211 Geneva 2, Switzerland +
Telephone: +41 (0) 22 730 84 03 +
Email: mailto:publications@wmo.int[] +
--
*URL*:: link:http://www.wmo.int/[www.wmo.int]
*Identifier*:: S-412
*Maintenance*:: Changes to the Product Specification S-412 are coordinated by the JCOMM, and must be made available via the IHO web site.

=== WMO Product Specification Maintenance

==== Introduction
Changes to S-412 will be released by the WMO as a New Edition, revision, or clarification.

==== New Edition
_New Editions_ of S-412 introduce significant changes. _New Editions_ enable new concepts, such as the ability to support new functions or applications, or the introduction of new constructs or data types. _New Editions_ are likely to have a significant impact on either existing users or future users of S-122. All cumulative _revisions_ and _clarifications_ must be included with the release of approved New Editions.

==== Revision
_Revisions_ are defined as substantive semantic changes to S-412. Typically, _revisions_ will change S-412 to correct factual errors; introduce necessary changes that have become evident as a result of practical experience or changing circumstances. A _revision_ must not be classified as a clarification. Revisions could have an impact on either existing users or future users of S-412. All cumulative _clarifications_ must be included with the release of approved _revisions_.

Changes in a revision are minor and ensure backward compatibility with the previous versions within the same Edition. Newer revisions, for example, introduce new features and attributes. Within the same Edition, a dataset of one version could always be processed with a later version of the Feature and Portrayal Catalogues.

In most cases a new feature or portrayal catalogue will result in a _revision_ of S-412.

==== Clarification
_Clarifications_ are non-substantive changes to S-122. Typically, _clarifications_: remove ambiguity; correct grammatical and spelling errors; amend or update cross references; insert improved graphics in spelling, punctuation and grammar. A _clarification_ must not cause any substantive semantic change to S-412.

Changes in a _clarification_ are minor and ensure backward compatibility with the previous versions within the same Edition. Within the same Edition, a dataset of one clarification version could always be processed with a later version of the Feature and Portrayal Catalogues, and a Portrayal Catalogue can always rely on earlier versions of the Feature Catalogue.


==== Version Numbers
The associated version control numbering to identify changes (n) to S-412 must be as follows:

New Editions denoted as **n**.0.0

Revisions denoted as n.**n**.0

Clarifications denoted as n.n.**n**
