
[[sec-overview]]
== Overview
=== Introduction
This document has been produced by the National Oceanic and Atmospheric Administration (NOAA) National Weather Service (NWS) Ocean Prediction Center (OPC) on behalf of the Joint World Meteorological Organization – Intergovernmental Oceanographic Commission (WMO-IOC) Technical Commission for Oceanography and Marine Meteorology (JCOMM), now WMO Commission for Weather, Climate, Hydrological, Marine, and Related Environmental Services and Applications (SERCOM), and the Worldwide Met-Ocean Information and Warning Service (WWMIWS) to define a data product that can be used as a Nautical Publication Information Overlay (NPIO) within electronic charting systems (ECS), including Electronic Chart Display and Information Systems (ECDIS). It has been developed within the framework specification defined by the International Hydrographic Organization (IHO) S-100 Universal Hydrographic Data Model and the International Standards Organization (ISO) 19100 series of standards. This product specification, S-412, is primarily intended for encoding marine weather warnings. These warnings include polygon portrayals of different hazardous weather conditions forecasted during the warning period to enhance situational awareness, route planning, and route monitoring.

=== Information
This product specification, S-412, is a vector graphic product specification that is primarily intended for encoding information on meteorological and oceanographic warnings that are used by mariners for route-planning, hazard avoidance, and risk mitigation. S-412 defines meteorological and oceanographic features, attributes and relationships, as well as their mapping to a dataset.

=== Scope
This document is maintained by the World Meteorological Organization (WMO) and describes an IHO S-100 compliant product specification for meteorological and oceanographic datasets, which will primarily act as an overlay for S-101 Electronic Navigational Charts on an S-100 based ECS, including ECDIS, in order to provide the maritime community with greater situational awareness. It specifies the content, structure, and metadata needed for creating a fully compliant Marine Weather Warnings dataset that will be compatible with an S-100 capable electronic navigation system. This product specification includes the content model, encoding guides, feature catalogue, portrayal catalogue, metadata, and example datasets.

In addition to acting as an overlay for S-101 Electronic Navigation Charts, this product specification outlines the capacity to interoperate with other S-100 compliant product specifications in accordance with the IHO S-98 Interoperability Specification.

This product specification does not include recommended changes to or requirements for services by National Meteorological and Hydrological Services.

[bibliography]
=== References

==== Normative references
GML OpenGIS®:: _Geography Markup Language (GML) Encoding Standard_ (Version 3.2.1).
NOAA National Weather Service Glossary:: _https://forecast.weather.gov/glossary.php._
National Weather Service Instruction 10-315:: _Marine Weather Message_, 2020 Edition.
National Weather Service Instruction 10-303:: _Marine and Coastal Services Standards and Guidelines_, 2022 Edition.
National Weather Service Instruction 10-604:: _Tropical Cyclone Names and Definitions_, 2021 Edition.
National Weather Service Instruction 10-811:: _Enroute Forecasts and Advisories_, 2022 Edition.
National Weather Service Policy Directive 10-6:: _Tropical Cyclone Weather Services Program_, 2020 Edition.
S-32:: _IHO Hydrographic Dictionary_, 2023 Edition.
S-53:: _Joint IHO/IMO/WMO Manual on Maritime Safety Information (MSI)_, January 2016 Edition.
S-98:: _Interoperability Specification_, 2022 Edition.
S-100:: _IHO Universal Hydrographic Data Model_, 2024 Edition._
S-101:: _IHO Electronic Navigation Chart Product Specification_, 2024 Edition._
WMO 8:: _Guide to Meteorological Instruments and Methods of Observation_, 2023 Edition.
WMO 182:: _International Meteorological Vocabular_, 1992 Edition.
WMO 306:: _Manual on Codes_, 2024 Edition.
WMO 386:: _Manual on the Global Telecommunication System_, 2020 Edition.
WMO 471:: _Guide to Marine Meteorological Services_, 2024 Edition.
WMO 485:: _Manual on the Global Data-processing and Forecasting System_, 2023 Edition.
WMO 558:: _Manual on Marine Meteorological Services_, 2024 Edition.
WMO 702:: _Guide to Wave Analysis and Forecasting_, 2020 Edition.
WMO/TD 850:: , 1998 Edition.
Global Maritime Distress and Safety System, GMDSS (weather.gov).
_IHO Geospatial Information Registry._
S-97:: _IHO Guidelines for Creating S-100 Product Specifications_, Edition 1.1.0, June 2020.
S-100:: _IHO Universal Hydrographic Data Model_, Edition 5.2.1, December 2025.

[bibliography]
==== Informative references
IMO A27/Res. 1051:: IMO/WMO Worldwide Met-Ocean Information and Warning Service, 2011 Edition.
ISO 8601. 2004:: _Data elements and interchange formats – Information interchange – Representation of dates and times_. 2004.
ISO 3166-1. 2020:: _Country Codes_. 2020.
ISO 639-2/T. 1998:: _Language Codes_. 1998.
ISO/TS 19103. 2024:: _Geographic information – Conceptual schema language_. 2024.
ISO/IEC 10646:2020:: _Information technology — Universal coded character set (UCS)_
ISO 19111. 2019:: _Geographic Information – Spatial referencing by coordinates_. 2019.
ISO 19115. 2003:: _Geographic Information – Metadata_. 2003.
ISO 19115-1. 2014:: _Geographic information - Metadata - Part 1: Fundamentals_. 2014.
ISO 19115-2.2019:: _Geographic Information – Metadata – Part 2: Extension for imagery and gridded data_. 2019.
ISO/TS 19123. 2005:: _Geographic information – Schema for coverage geometry and functions_. 2005.
ISO/TS 19123-1. 2023:: _Geographic information – Schema for coverage geometry and functions. Part 1: Fundamentals_. 2023.
ISO 19129. 2009:: _Geographic information – Imagery, gridded and coverage data framework_. 2009.
ISO 19131. 2022:: _Geographic information – Data product specifications_. 2022.
ISO 19136:2007:: _Geographic Information – Geographic Markup Language (GML)_. 2007.
ISO 19136-1:2020:: _Geographic Information – Geographic Markup Language (GML). Part 1: Fundamentals_. 2020.
ISO/IEC 19501. 2005:: _Information technology – Unified Modeling Language (UML) Version 1.4.2_. 2005
ISO 19101:2002:: _Geographic information – Reference model_. 2002.
ISO 19101-1:2014:: _Geographic information – Reference model. Part 1: Fundamentals_. 2014.
ISO 19103: 2024:: _Geographic information – Conceptual schema language_. 2024.
ISO 19105: 2022:: _Geographic information – Conformance and testing_. 2022.
ISO 19107:2019:: _Geographic information – Spatial schema_. 2019.
ISO 19108:2002:: _Geographic information – Temporal schema_. 2002.
ISO 19109:2015:: _Geographic information – Rules for application schema_. 2015.
ISO 19110: 2016:: _Geographic information – Methodology for feature cataloguing_. 2016.
ISO 19113: 2005:: _Geographic information – Quality principles_. 2005
ISO 19116: 2019:: _Geographic information – Positioning services_. 2019.
ISO 19117:2012: _Geographic information – Portrayal_. 2012.
ISO 19118: 2011:: _Geographic information – Encoding_. 2011.
ISO 19128:2005:: _Geographic information – Web Map Server interface_. 2005.
19132: 2007:: _Geographic information – Location-based services – Reference model_. 2007.
ISO 19133:2005:: _Geographic information – Location-based services – Tracking and navigation_. 2005.
ISO 19138:2006:: _Geographic information – Data quality measures_. 2006.
ISO 19142:2010:: _Geographic information – Web Feature Service_. 2010.
ISO 19144-1:2009:: _Geographic information – Classification systems – Part 1: Classification system structure_. 2009.
ISO 19145:2013:: _Geographic information – Registry of representations of geographic point location_. 2013.
ISO 19153:2014:: _Geographic information – Geospatial Digital Rights Management Reference Model (GeoDRM RM) 1)_. 2014.
ISO 19156:2023:: _Geographic information – Observations and measurements_. 2011.
ISO 19157:2023:: _Geographic information – Data quality_. 2013.
ISO/TS 19158:2012:: _Geographic information – Quality assurance of data supply_. 2010.
ISO 19101:: _Geographic Information – Reference Model_, 2003.
ISO 19103:: _Geographic Information – Conceptual Schema Language_, 2005.
ISO 19103-2:: _Geographic Information – Conceptual Schema Language – Part 2_, 2005.
ISO 19109:: _Geographic Information – Rules for Application Schema_, 2005.
ISO 19110:: _Geographic Information – Methodology for Feature Cataloguing_, 2005.
ISO 19111:: _Geographic Information – Spatial Referencing by Coordinates_, 2007.
ISO 19115-1:: _Geographic information - Metadata - Part 1: Fundamentals_ - 2014/Amd 1: 2018.
ISO 19115-3:: _Geographic information - Metadata - Part 3: XML Schema implementation for fundamental concepts_ - 2016.
ISO 19117:: _Geographic Information – Portrayal_, 2012.
ISO 19131:: _Geographic Information – Data Product Specifications_, 2008.
ISO 19139-1:: _Geographic information - XML schema implementation - Part 1: Encoding rules_ - 2019

=== Terms, definitions and abbreviations

==== Use of language

Within this document:

* "`Must`" indicates a mandatory requirement.
* "`Should`" indicates an optional requirement, that is the recommended process to be followed, but is not mandatory.
* "`May`" means "`allowed to`" or "`could possibly`" and is not mandatory.

The S-100 framework is based on the ISO 19100 series of geographic standards. The terms and definitions provided here are used to standardise the relevant nomenclature found within that framework, whenever possible. Additional definitions specific to S-412 are provided in this section as well. Features, attributes and associations that may be realised in an S-412 compliant dataset are defined in Annex A, B and C.

==== Terms and definitions

*Abstract Class*
An object class which cannot be instantiated, or is designated in an information model as not allowed  to be instantiated [ISO 19107].

NOTE:: subclasses of an abstract class may be either abstract or non-abstract.

*Aggregation*

Special form of association that specifies a whole-part relationship between the aggregate (whole) and a component part (see composition) [ISO 19103].

*Application*

Manipulation and processing of data in support of user requirements [ISO 19101-1:2014].

*Application Schema*

Conceptual schema for data required by one or more applications [ISO 19101].

*Association*

Semantic relationship between two or more classifiers that specifies connections among their instances [ISO 19101].

NOTE:: A binary association is an association among exactly two classifiers (including the possibility of an association from a classifier to itself).

*Attribute*

(1) Named property of an entity [ISO/IEC 2382-17:1999].

NOTE:: Describes a geometrical, topological, thematic, or other characteristic of an entity.

(2) Feature within a classifier that describes a range of values that instances of the classifier may hold.

NOTE:: An attribute is semantically equivalent to a composition association; however, the intent and usage is normally different.

NOTE:: “Feature” used in this definition is the UML meaning of the term.

*Boundary*

Set that represents the limit of an entity.

NOTE:: Boundary is most commonly used in the context of geometry, where the set is a collection of points or a collection of objects that represent those points.

*Class*

Description of a set of objects that share the same attributes, operations, methods, relationships, and semantics [ISO/TS 19103:2005].

NOTE:: a class represents a concept within the system being modelled. Depending on the kind of model, the concept may be real-world (for an analysis model), or it may also contain algorithmic and computer implementation concepts (for a design model). A classifier is a generalisation of class that includes other class-like elements, such as data type, actor and component.

*Code List*

Value domain including a code for a permissible value [ISO 19136].

*Coordinate*

One of a sequence of _n_ numbers designating the position of a *point* in N-dimensional space [ISO 19111].

NOTE:: In a *coordinate reference system*, the coordinate numbers are qualified by units [ISO 19107, ISO 19111].

*Coordinate Reference System*

A coordinate system that is related to the real world by a datum [ISO 19111].

NOTE:: for geodetic and vertical datums, it will be related to the Earth.

*Coverage*

Feature that acts as a function to return values from its range for any direction position within its spatial, temporal, or spatiotemporal domain [ISO 19123:2005].

Example: Examples include a raster image, polygon overlay, or digital elevation matrix type.

*Curve*

1-dimensional geometric primitive, representing the continuous image of a line[ISO 19107].

NOTE:: The boundary of a curve is the set of points at either end of the curve. If the curve is a cycle, the two ends are identical, and the curve (if topologically closed) is considered to not have a boundary. The first point is called the start point, and the last is the end point. Connectivity of the curve is guaranteed by the "continuous image of a line" clause. A topological theorem states that a continuous image of a connected set is connected.

*Data Product*

A dataset or dataset series that conforms to a data product specification [ISO 19131].

*Dataset*

Identifiable collection of data [ISO 19115].

NOTE:: A dataset may be a smaller grouping of data which, though limited by some constraint such as spatial extent or feature type, is located physically within a larger dataset. Theoretically, a dataset may be as small as a single feature or feature attribute contained within a larger dataset. A hardcopy map or chart may be considered a dataset.

*Data Quality*

A set of elements describing aspects of quality, including a measure of quality, an evaluation procedure, a quality result, and a scope.

*Data Type*

Specification of a value domain with operations allowed on values in this domain [ISO/TS 19103:2005].

Example: Integer, Real, Boolean, String, Date

NOTE:: Data types include primitive predefined types and user-definable types.

NOTE:: A data type is identified by a term, for example Integer.

*Datum*

_Parameter or set of parameters that define the position of the origin, the scale, and the orientation of a *coordinate* system._

*ECDIS*

"Electronic Chart Display and Information System". A navigation information system which with adequate back-up arrangements can be accepted as complying with the up-to-date chart required by regulations V/19 and V/27 of the 1974 SOLAS Convention, as amended, by displaying selected information from a System Electronic Navigational Chart (System Database) with positional information from navigation sensors to assist the Mariner in route planning and route monitoring, and if required display additional navigation-related information.

*Direct Position*

Position described by a single set of coordinates within a coordinate reference system [ISO 19107].

*Enumeration*

A fixed list of valid identifiers of named literal values. Attributes of an enumerated type may only take values from this list.

*Feature*

Abstraction of real-world phenomena [ISO 19101:2003].

Example: The phenomenon truck may be classified with other similar phenomena into a feature type named automobile.

NOTE:: A feature may occur as a type or an instance. Feature type or feature instance should be used when only one is meant.

*Feature Attribute*

Characteristic of a *feature* [ISO 19101].

NOTE:: A feature attribute type has a name, a data type, and a domain associated to it. A feature attribute instance has an attribute value taken from the value domain of the feature attribute type.

Example: A feature attribute named ‘colour’ may have an attribute value ‘green’ which belongs to the data type ‘text’.

*Feature Catalogue*

A catalogue containing definitions and descriptions of the *feature* types, *feature attributes* and occurring in one or more sets of geographic data [ISO 19110].

*Geometric Object*

Spatial object representing a set of direction positions [ISO 19107].

NOTE:: _A geometric object consists of a geometric primitive, a collection of geometric primitives, or a geometric complex treated as a single entity. A geometric object may be the spatial characteristics of an object such as a feature or a significant part of a feature._

*_Geometric Primitive_*

_Geometric object representing a single, connected, homogeneous element of geometry._

NOTE:: _Geometric primitives are non-decomposed objects that present information about geometric configuration. They include points, curves and surfaces._

*Generalisation*

Taxonomic relationship between a more general element and a more specific element [ISO 19103].

NOTE:: The more specific element is fully consistent with the more general element and contains additional information. An instance of the more specific element may be used where the more general element is allowed.

*Inheritance*

Mechanism by which more specific elements incorporate structure and behavior of more general elements related by behavior [ISO 19103].

*Map Projection*

Coordinate conversion from an ellipsoidal coordinate system to a plane [ISO 19111].

*Maritime Zone*

Zones recognized under international law include internal waters, the territorial sea, the contiguous zone, the exclusive economic zone (EEZ), the continental shelf, the high seas, and the Area [NOAA] Maritime Zones and Boundaries | National Oceanic and Atmospheric Administration (noaa.gov).

*Metadata*
Data about data [ISO 19115:2005].

*METAREA*

METAREA is the acronym for METeorological AREA. It means a geographical sea area established for the purpose of co-ordinating the broadcast of marine meteorological information. The term METAREA followed by a roman numeral may be used to identify a particular sea area. [WMO List of METAREAS].

*Multiplicity*

Specification of the number of possible occurrences of a property, or the number of allowable elements that may participate in a given relationship [ISO 19103].

Examples: 1..* (one to many); 1 (exactly one); 0..1 (zero or one).

*Numerical Model*

Computer simulations of the atmosphere and/or ocean that use an analysis of the current weather as a starting point to project the future state and provide the foundation of the weather forecasts. [Adapted from NOAA (https://www.weather.gov/rah/virtualtourforecast)].

*Object*

Entity with a well-defined boundary and identity that encapsulates state and behavior.
Note: State is represented by attributes and relationships, behavior is represented by operations, methods, and state machines. An object is an instance of a class. [S-100].

*_Point_*

_0-dimensional geometric primitive, representing a position._

NOTE:: _The boundary of a point is the empty set._

*Portrayal*

Presentation of information to humans [ISO 19117].

NOTE:: within the scope of this International Standard portrayal is restricted to the portrayal of geographic information. [S-100].

*Portrayal Catalogue*

Collection of defined portrayals for a feature catalogue.

NOTE:: Content of a portrayal catalogue includes portrayal functions, symbols, and portrayal context [ISO 19117:2012 (E), 4.21].

*Portrayal Rule*

Specific type of portrayal function expressed in a declarative language.

NOTE:: A declarative language is rule-based and includes decision and branching statements. [ISO 19117:2012 (E), 4.25].

*Range <Coverage>*

Set of values associated by a function with the elements of the spatiotemporal domain of a coverage. [ISO 19123].

*Realization*

Relationship between a specification and its implementation [ISO 19103].

*Record*

Finite, named collection of related items (objects or values) [ISO 19107].

NOTE:: Logically, a record is a set of pairs <name, item>.

*Register*

Set of files containing identifiers assigned to items with descriptions of the associated items [ISO 19135].

NOTE:: Descriptions may consist of many types of information, including names, definitions and codes.

*Register Manager*

Organization to which management of a register has been delegated by the register owner. [ISO 19135].

NOTE:: In the case of an IHO Register, the Register Manager performs the functions of the registration authority specified in the IHO Directives.

*Register Owner*

Organization that establishes a register [S-100].

*Registry*

Information system on which a register is maintained. [ISO 19135].

*Schema*
Formal description of a model [S-100].

Applied.*Significant Wave Height*

The average trough-to-crest height of the highest one third of the wave heights (sea and swell) occurring in a particular time period [WMO Glossary].

*Spatial Reference*

Description of position in the real world [S-100].

*Start Point*

First point of a curve. [ISO 19107].

*Submitting Organization*

Organization authorized by a register owner to propose changes to the content of a register. [ISO 19135].

*Surface (Geometry)*

2-dimensional geometric primitive, representing the continuous image of a region of a plane [ISO 19107].

NOTE:: The boundary of a surface is the set of oriented, closed curves that delineate the limits of the surface.

*Symbol*

Portrayal primitive such as line styles, patterns, text and point symbol graphics defined in SVG. [S-100].

*Type*

Stereotype of class that is used to specify a domain of instances (objects) together with the operations applicable to the objects.

NOTE:: A type may have attributes and associations [S-100].

*Unit*

Defined quantity in which dimensioned parameters are expressed. [S-100].

*Value*

Element of a type domain [ISO/TS 19103:2005].
NOTE 1:: A value may be considered a possible state of an object within a class or type (domain).

NOTE 2:: A data value is an instance of a data type, a value without identity.

==== Abbreviations
This Product Specification adopts the following convention for presentation purposes:

CRS::  Coordinate Reference System
DCEG::  Data Classification and Encoding Guide
ECDIS:: Electronic Chart Display and Information System
ECS:: 	Electronic Chart System (Non SOLAS) 
ENC::  Electronic Navigational Chart
EPSG::  European Petroleum Survey Group [https://epsg.org/]
ET-MS::  Expert Team on Maritime Safety
FCD::		Feature Concept Dictionary
GFM::		General Feature Model
GI::  Geospatial Information
GMDSS:: 	Global Maritime Distress and Safety System
GML:: Geography Markup Language
HDF5::		Hierarchical Data Format (HDF5 is the fifth release)
ICC::  International Color Consortium 
IHO:: International Hydrographic Organization
IMO::		International Maritime Organization
IOC::		Intergovernmental Oceanographic Commission
ISO:: International Organization for Standardization
JCOMM:: Joint Technical Commission for Oceanography and Marine Meteorology
METAREA::  METeorological AREA
OEM::		Original Equipment Manufacturer 
S-100WG:: 	S-100 Working Group
SC-MMO::  Standing Committee on Marine Meteorological and Oceanographic Services 
SERCOM::  Commission for Weather, Climate, Hydrological, Marine, and Related Environmental Services and Applications
SOLAS::		International Convention for Safety of Life at Sea
SVG::		Scalable Vector Graphics
UML::		Unified Modelling Language
URI::		Uniform Resource Identifier
URL::		Universal Resource Locator
UTC::		Coordinated Universal Time
UTF-8::  Unicode Transformation Format-8
WMO::  World Meteorological Organization
WWMIWS::	Worldwide Met-Ocean Information and Warning Service
XML::		Extensible Mark-up Language
XSD::		World Wide Web Consortium XML Schema Definition
XSLT::		eXtensible Stylesheet Language Transformations

=== General Marine Weather Warnings Data Product Description

*Title*:: S-412 Marine Weather Warnings

*Abstract*:: This data product describes real-world weather and oceanographic warnings created from authoritative maritime weather analysis and forecast data products. These S-100-compliant weather warnings will be used by mariners for route-planning and hazard mitigation.

*Acronym*:: S-412

*Content*:: The Product Specification defines all requirements to which Marine Weather Warnings data products must conform. Specifically it defines the data product content in terms of features and attributes within the feature catalogue. The display of polygons is defined by the features and rule sets contained in the portrayal catalogue. The Data Classification and Encoding Guide (DCEG) provide guidance on how data product content must be captured.

*Spatial Extent*::

*Description*: Maritime zones and terrestrial locations within proximity of navigable waters. +

*East Bounding Longitude*: 180° +
*West Bounding Longitude*: -180° +
*North Bounding Latitude*: 90° +
*South Bounding Latitude*: -90° +

*Purpose*:: 
*Navigation* +
The purpose of a Marine Weather Warnings dataset is to enhance the situational awareness and decision-making capacity of a mariner, as well as warn mariners of adverse, hazardous, dangerous, or extreme conditions that may pose a threat to life or property. +
An S-412 product can be used as an overlay for electronic navigational charts within shipboard or shore side navigation systems or as a standalone product within an appropriate geographic information system display.

=== Data Product Specification metadata

*Title*:: S-412 Marine Weather Warnings Product Specification
*S-100 Version*:: 5.2.0
*S-412 Version*:: 1.2.0
*Date*:: 23 January 2026
*Language*:: English (optional additional)
*Classification*:: Unclassified
*Contact*::  World Meteorological Organization +
7bis, avenue de la Paix +
Case postale 2300 +
CH -1211 Geneva 2 +
Switzerland
Telephone: +41 (0) 22 730 84 03 +
Email: mailto:publications@wmo.int[] +

*URL*:: link:http://www.wmo.int/[www.wmo.int]

*Identifier*::  S-412 +
*Maintenance*::  Changes to the Product Specification S-412 are coordinated by the SERCOM, formely JCOMM, and must be made available via the IHO web site. When a new version of the product spec is ready for approval it must follow through several bodies of the WMO; including: ET-MS and SC-MMO while keeping WWMIWS aware of changes for METAREAS. Once approved by the WMO, the WMO’s Domain Control Body Member will submit the document to IHO for approval into the GI Registry. +

*URL*:: link:http://www.wmo.int/[www.wmo.int]
*Identifier*:: S-412

=== Product Specification Maintenance

==== Introduction
Changes to this product specification are coordinated by the WMO Commission for Weather, Climate, Hydrological, Marine, and Related Environmental Services and Applications (SERCOM), Standing Committee on Marine Meteorological and Oceanographic Services (SC-MMO), and WorldWide Met-ocean Information and Warning Service (WWMIWS). Changes to the Marine Weather Warnings will be released by the WWMIWS as a new edition, revision, or clarification. Requests for specific changes to this product specification should be coordinated through the most convenient National Meteorological Service or directly to WWMIWS.

==== New Edition
_New Editions_ of S-412 introduce significant changes. _New Editions_ enable new concepts, such as the ability to support new functions or applications, or the introduction of new constructs or data types. _New Editions_ are likely to have a significant impact on either existing users or future users of S-412. All cumulative _revisions_ and _clarifications_ must be included with the release of approved New Editions.

==== Revision
_Revisions_ are defined as substantive semantic changes to S-412. Typically, _revisions_ will change S-412 to correct factual errors; introduce necessary changes that have become evident as a result of practical experience or changing circumstances. A _revision_ must not be classified as a clarification. Revisions could have an impact on either existing users or future users of S-412. All cumulative _clarifications_ must be included with the release of approved _revisions_.

Changes in a revision are minor and ensure backward compatibility with the previous versions within the same Edition. Newer revisions, for example, introduce new features and attributes. Within the same Edition, a dataset of one version could always be processed with a later version of the Feature and Portrayal Catalogues.

In most cases a new feature or portrayal catalogue will result in a _revision_ of S-412.

==== Clarification
_Clarifications_ are non-substantive changes to S-412. Typically, _clarifications_: remove ambiguity; correct grammatical and spelling errors; amend or update cross references; insert improved graphics in spelling, punctuation and grammar. A _clarification_ must not cause any substantive semantic change to S-412.

Changes in a _clarification_ are minor and ensure backward compatibility with the previous versions within the same Edition. Within the same Edition, a dataset of one clarification version could always be processed with a later version of the Feature and Portrayal Catalogues, and a Portrayal Catalogue can always rely on earlier versions of the Feature Catalogue.

==== Version Numbers
The associated version control numbering to identify changes (n) to S-412 must be as follows:

New Editions denoted as **n**.0.0

Revisions denoted as n.**n**.0

Clarifications denoted as n.n.**n**





