
[[sec-data-product-identification]]
== Data Product Identification

A dataset that conforms to this Product Specification may be identified by its discovery metadata as defined in clause 12.

*Title*:: Marine Weather Warnings

*Abstract*:: 
S-412 datasets must be produced in accordance with the rules defined in this S-412 Product Specification. The S-412 Product Specification contains all the information necessary to enable meteorological organisations to produce a consistent overlay, and manufacturers to use that data efficiently in an electronic navigation systems. +
Compliant datasets of Marine Weather Warnings contain polygons of hazardous meteorological and oceanographic conditions. Datasets are produced by an authoritative weather forecasting agency for a particular geographic region and set of times, and may include accompanying metadata describing the content, variables, applicable times, locations, and structure of the data product. Data used to create the polygons may be derived from observed, mathematically-predicted, or model-driven phenomena.

*Topic Category*:: Climatology, Meteorology, Atmosphere (ISO 19115 Domain Code 004) - Oceans (ISO 19115 Domain Code 014)

*Geographic Description*:: The geographic boundaries of warning polygons are determined by meteorological events for a given time period; however, the warnings are only provided over maritime regions.

*Spatial Resolution*:: 
The spatial resolution varies by weather forecasting agency and is largely determined by their forecasting and analysis domain and file size of each data file. +
Producers should note that at the smaller scales, geographic details will have no perceptible visual separation on a graphic display, and are therefore encouraged to determine display scales taking into account the content and intended navigation purpose of the dataset.

*Purpose*:: Navigation in all regions. The Marine Weather Warnings dataset is primarily intended to be used in electronic navigation systems as an overlay to an ENC.

*Language*:: English (Mandatory), other (Optional)

*Classification*:: Data may be classified as one of the following:

. Unclassified;
. Restricted;
. Confidential;
. Secret;
. Top Secret;
. Sensitive but Unclassified;
. For official Use Only;
. Protected;
. Limited Distribution.

*Spatial Representation Type*:: Vector

*Point of Contact*:: Dataset Producing Agency

*Use Limitation*:: Must be used with an ENC. An S-412 dataset is not intended to be used for land-based or aviation weather forecasting purposes.
