
[[sec-data-content-and-structure]]
== Data Content and Structure

=== Introduction

=== Application Schema

==== Domain model

==== S-412 Features

===== Meta Features

===== Geographic Features

==== Attributes

S-412 defines attributes as either simple or complex in line with the S-100 GFM.

===== Simple attributes

S-412 uses 3 types of simple attributes; these types are listed in Annex A – Data Classification and Encoding Guide, clause 2.4.2. Descriptions of the simple attributes included in S-412 can be found in Annex A, Sections 27, 28 and 30.

===== Complex attributes

Complex attributes are aggregations of other attributes that are either simple or complex. The aggregation is defined by means of attribute bindings. Examples of modelling complex attributes can be found in S-100 Part 2a, Appendix 2a-A. Descriptions of the complex attributes included in S-412 can be found in Annex A – Data Classification and Encoding Guide

=== Feature Catalogue

==== Introduction

The S-412 Feature Catalogue describes the feature types, attributes and attribute values which may be used in an S-412 product.

The S-412 Feature Catalogue is available as an XML document which conforms to the S-100 XML Feature Catalogue Schema and can be downloaded from the IHO website (https://registry.iho.int/). S-412 Annex A – Data Classification and Encoding Guide, constitutes a human readable interpretation of the Feature Catalogue along with information on how features should be encoded.

The feature Catalogue contains only geographic and meta features. The  features which can be used in ECDIS are defined within the WMO domain of the IHO Registry.

==== Feature types

Feature types contain descriptive attributes that characterize real-world entities. The word ‘feature’ may be used in one of two senses – feature type and feature instance. A feature type is a class and is defined in a Feature Catalogue. A feature instance is a single occurrence of the feature type and represented as an object in a dataset. A feature instance is located by a relationship to one or more spatial instances. A feature instance may exist without referencing a spatial instance.

==== Geographic

Geographic (geo) feature types carry the descriptive characteristics of a real-world entity (a location or place on the surface of the Earth). In the context of Information products, this comprises most of the features (with the exception of DataCoverage) and represents those features with a real-world existence.

==== Meta

**QN - is data coverage needed? **

Only one metadata feature is defined, DataCoverage. This defines the area of coverage bounded by the dataset, and any features within it. DataCoverage contains a mandatory optimumDisplayScale attribute and two optional maximum, and minimum display scale attributes.

==== Attributes

S-412 defines attributes as either simple or complex in line with the S-100 GFM.

===== Simple attributes

**Add as appropriate **

S-412 uses three types of simple attributes; they are listed in the following Table:

[cols="a,a",options="headers"]
|===
|Type |Definition 

|Integer
|An integer number.

|Real
|A floating point number.

|Enumeration
|One or more of a list of predefined values.

|===

==== Application Schema implementation

===== Implementation description

==== Feature Types Summary

. Summary of implemented features
[width=50%,cols="1,1,5",options="headers"]
|===
|Index |Alias |Name

|Feature
|Weather Warning
|Weather Warning

|===
