
[[sec-coordinate-reference-systems-crs]]
== Coordinate Reference Systems (CRS)

=== Introduction

When describing geographic information, it is common practice to separate the horizontal and vertical part of a position. This leads to 2D Coordinate Reference Systems for the horizontal positions and 1D Coordinate Reference Systems for the vertical positions. 

[[horizontal-crs]]
=== Horizontal Coordinate Reference System

The horizontal coordinate reference system used for this product specification must be the World Geodetic System 1984 (WGS84) - (EPSG:4326) which is defined by the European Petroleum Survey Group (EPSG) code 4326. The longitude is stored as a negative number to represent a position west of the prime Meridian. Latitude is stored as a negative number to represent a position south of the Equator.

*Horizontal Coordinate Reference System*:: EPSG:4326 (WGS84)
*Projection*:: NONE
*_Temporal reference system_*:: _Gregorian Calendar_
*Coordinate Reference System registry*:: link:https://epsg.org/[EPSG Geodetic Parameter Dataset]
*Date type (according to <<iso-19115-1>>)*:: 002 - publication
*Responsible party*:: International Association of Oil and Gas Producers (IOGP)
*URL*:: http://www.iogp.org/

=== Vertical Coordinate Reference System
This product specification does not apply to meteorological or oceanographic features at multiple vertical levels. All Weather Warning polygons are developed as overlays within ECS and thus are valid at the vertical datum defined by the ENC.

_In this product there are no direct vertical coordinates which require the use of a vertical coordinate reference system._

=== Temporal reference system

The Marine Weather Warnings Product Specification applies to meteorological features valid at specific times. The temporal reference system used is the Gregorian calendar for date and UTC for time. Time is measured by reference to Calendar dates and Clock time in accordance with ISO 19108:2002 Temporal Schema clause 5.4.4. Times must be in UTC and follow the following 25-character format: yyyymmddThhmmss.

_The temporal reference system is the Gregorian calendar for date and UTC for time. Time is measured by reference to Calendar dates and Clock time in accordance with <<iso-8601,clause=5.4.4>>. A date-time variable will have the following 16-character format: _yyyymmddThhmmssZ_._
