
[[sec-data-product-format-encoding]]
== Data Product Format (encoding)

=== Introduction

This clause specifies the encoding for Marine Weather Warning datasets. The principal encoding is the Open Geospatial Consortium (OGC), Geography Markup Language (GML) format as profiled by the S-100 GML schema in Part 10b of S-100.

The XML Schema for the S-412 GML application schema is available at the GI Registry (http://registry.iho.int). Feature instances must validate against the schema and conform to all other requirements specified in this data product specification including all constraints not captured in the XML Schema document.

=== Encoding of Latitude and Longitude

Values of latitude and longitude can be accurate up to 7 decimal places. Coordinate values should be coded as decimal numbers with 7 or fewer digits after the decimal. The normative encoding is in degrees, with an accuracy of 10-7 degrees; that is, up to 7 digits after the decimal point.

=== Text Attribute Values

Character strings must be encoded using the character set defined in ISO 10646:2020, in Unicode Transformation Format-8 (UTF-8). A BOM (byte order mark) must not be used.

=== Temporal Attribute Encoding

Times must be in UTC and follow the following 16-character format: _yyyymmddThhmmssZ._

=== Mandatory Attribute Values

There are five reasons why attribute values may be considered mandatory: +
●	They determine whether a feature is to be displayed; +
●	Certain features make no logical sense without specific attributes; +
●	Some attributes are necessary to determine portrayal elements; +
●	Certain attributes are used to verify data quality; +
●	Some attributes are required for safety of navigation.

All mandatory attributes are identified in the Feature catalogue and summarised in the Data Classification and Encoding Guides provided in Annex A. 

=== Missing or Unknown Attribute Values

Missing or unknown values are not permitted in S-412. Mandatory attributes must contain meaningful data.

=== Encoding Datasets Across 180° Longitude

Datasets must not cross the 180° meridian of longitude; this includes the bounding box for the dataset.

=== Message Filtering Along Routes

< < Statement regarding systems ability to filter information along a route by date, time, and conditions > >
