
[[sec-data-product-delivery]]
== Data Product Delivery

=== Format Specification

At the moment there is only one type of dataset supported. This is GML encoded ice feature collections according to S-100 Part 10b.

=== Introduction

=== Exchange Set

=== Exchange Catalogue

==== Exchange Catalogue Naming

==== Dataset size

==== Dataset file naming
Dataset naming must follow a standard pattern to give implementers greater predictability of incoming datasets (see <<iho-s100,part=17,clause=4.3>>). S-412 dataset naming conventions must follow these rules and no further restrictions are made in this product specification.

*412YYYYØØØØØØØØØØØØ.GML*::
412::: the first 3 characters identify the dataset as an S-412 dataset (mandatory).
YYYY::: the fourth to seventh characters identify the producer code according to the Producer Code Register.
ØØØØ::: the eighth to the maximum nineteenth characters are optional and may be used in any way by the producer to provide the unique file name. The following characters are allowed in the dataset name: A to Z, 0 to 9 and the special character _ (underscore).
GML::: denotes a GML file (according to <<iho-s100,part=10b>>).

=== Exchange Set


=== Support Files
No support files are included in any of the S-412 features currently. If they are supported in the future then their specification and delivery will be added to this section.

=== Exchange Catalogue
The Exchange Catalogue acts as the table of contents for the Exchange Set. The Catalogue file of the Exchange Set must be named CATALOG.XML. No other file in the Exchange Set may be named CATALOG.XML. The contents of the Exchange Catalogue are described in <<sec-metadata>>.

=== Data integrity and encryption
<<iho-s100,part=15>> defines the algorithms for compression, encrypting and digitally signing datasets based on the S-100 Data Model. Use of encryption is optional. Digital Signatures are mandatory for all datasets.

==== Use of compression
The data producer decides if compression will be used on the S-412 product files (GML). It is expected that a hydrographic office will make a policy decision and that all the S-412 datasets from the producer will be either compressed or uncompressed.

It is recommended to compress all the dataset files. The ZIP compression method defined in <<iho-s100,part=15,clause=5.2>> should be used where applicable.

==== Use of digital signatures
Digital signatures must be used on all files included in a S-412 compliant Exchange Set to meet the requirements of IMO resolution MSC.428(98) to reduce cyber security risks among users, especially when used in navigations systems at sea. The recommended signature method is defined in <<iho-s100,part=15>>.

The digital signature information is encoded in the corresponding discovery block in the exchange catalogue for each file included in the Exchange Set as defined in <<iho-s100,part=17>>.
