
[[annex-validation-checks]]
[appendix]
== Validation Checks

#This annex has been initiated based on S-158 and S-102 Validation Checks Annex. It is still to be amended to fit with S-412 specificities and completed with S-412 validation checks.#

=== Introduction
The following checks are intended for production systems designed to produce S-412 datasets. The checks can be administered at any time during the production phase. They can also be applied downstream in the distribution and end user systems to test the conformance of a dataset to the format rules specified in S-100 Part 10c and the S-412 Product Specification.

==== References

===== Normative references

*  CLE92:: _ClementinI, E., Di Felice, P., Van Oostrom, P. A Small Set of Formal Topological Relationships Suitable for End-User Interaction, in D. Abel and B. C. Ooi (Ed.), Advances in Spatial Databases — Third International Symposium. SSD 1993. LNCS 692, pp. 277-295._ Springer Verlag. Singapore (1993).
*  ISO 19107:2003:: _Geographic Information – Spatial Schema_.
*  ISO 19125-1:2004:: _OpenGIS Simple Features Specification for SQL, Revision 1.1 (OpenGIS Project Document 99-049,_ Release Date: May 5, 1999).
*  S-100:: _IHO Universal Hydrographic Data Model,_ Edition 5.2.0, June 2024

===== Informative references
*  ISO 19157:2013:: _Geographic information – Data Quality._ As amended by Amendment 1, 2018

==== Terms, definitions and abbreviations

===== Terms and definitions

Definitions hereafter complete the list provided in Section 1-Overview.

*conformance*:: fulfilment of specified requirements [ISO 19105].
*data quality*:: a set of elements describing aspects of quality, including a measure of quality, an evaluation procedure, a quality result, and a scope.
*data quality element*:: quantitative component documenting the quality of a dataset [ISO 19101:2002] +
NOTE: The applicability of a data quality element to a dataset depends on both the dataset’s content and its product specification, the result being that all data quality elements may not be applicable to all datasets.
*data quality measure*:: an evaluation of a data quality sub-element [ISO 19113].
*data quality overview element*:: the non-quantitative component documenting the quality of a dataset. Information about the purpose, usage, and lineage of a dataset is non-quantitative quality information.
NOTE Information about the purpose, usage and lineage of a dataset is non-quantitative quality information. [ISO 19101].
*data quality scope*:: the extent or characteristic(s) of the data for which quality information is reported [ISO 19113] NOTE: A data quality scope for a dataset can comprise a dataset series to which the dataset belongs, the dataset itself, or a smaller grouping of data located physically within the dataset sharing common characteristics. Common characteristics can be an identified feature type, feature attribute, or feature relationship; data collection criteria; original source; or a specified geographic or temporal extent. [S-100 Annex A].
*data quality sub-element*:: a component of a data quality element describing a certain aspect of that data quality element [ISO 19103].
*measurement*:: the (detailed) dimensions of a physical quantity [S-32].
*record*:: finite, named collection of related items (objects or values).

===== Abbreviations

#Not sure this section is needed.#

===== Symbols

#To be completed based on equivalent section in S-158.#

=== Check Classification
Checks are classified as Critical, Error, or Warning checks as described in the Table below.

[[tab-check-classification]]
.Classification of checks
[cols="a,a,a",options="header"]
|===
|Category Code | Category Name | Category Description

| C	| Critical Error	| An error which would make a dataset unusable in ECDIS through not loading or causing an ECDIS to crash or presenting data which is unsafe for navigation.

| E	| Error	| An error which may degrade the quality of the dataset through appearance or usability but which will not pose a significant danger when used to support navigation.

| W	| Warning	| An error which may be duplication or an inconsistency which will not noticeably degrade the usability of a dataset in ECDIS.

|===

=== Check Application

The checks apply to each GML file which constitutes a dataset (in the S-100 sense of “dataset” as an entire GML file).

There being no update dataset format defined in S-412, checks are not designated as applying to “base” or “update” datasets.

=== Validation Steps
==== Dataset validation

Dataset validation checks the structure and content of individual GML data files. The checks for each HDF5 dataset file are divided into five phases:

[[tab-phases-in-validation-processing-for-HDF5-datasets]]
.Phases in validation processing for HDF5 datasets
[cols="a,a,a",options="header"]
|===
| Phase	| Name	| Description

| 1	| Validate Dataset Root and Feature Information	| Validation of root group of HDF5 file and feature type information.

| 2	| Validate Feature Container Groups	| Validation of metadata and structure for each feature type (“Feature Container”). In S-102 there are two feature containers (one for the bathymetry data and another for survey information), so this set of checks is executed only once for each. If future Editions introduce more feature container HDF5 groups, this set must be executed for each feature container HDF5 group.

| 3	| Validate Feature Instance Groups	| Validation of feature instances. This set of checks, along with Phase 4 and 5 checks, must be executed once for each feature instance group contained within a feature container.

| 4	| Validate Values Datasets	| Validation of bathymetry data values. This set of checks is applied to the values group in a feature instance group.

| 5 | Validate Quality Information | Validation of quality information. This set of checks is applied to the QualityOfBathymetryCoverage group and executed if and only if that group is present.

|===

Certain check failures in earlier phases prevent progress to later phases (for example, because information for the later phase is not available). If such checks fail, processing of other checks in the current phase may continue, but subsequent phases cannot be executed due to a lack of necessary information.

==== Exchange Set validation (informative)

Exchange Set validation involves the following phases.

. Checking the presence and correctness of the Exchange Catalogue (CATALOG.XML).

. Verification of signatures, including the Exchange Catalogue signature and signatures for individual datasets, catalogues, and support files.

. Checking the structure and contents of the Exchange Set package, including whether there is a discovery block for each file in the Exchange Set.

. Checking that the metadata encoded in a discovery block and the headers and embedded metadata in the corresponding dataset or Catalogue are compatible.

Generalised checks for Exchange Set validation are being developed by the S-100WG and will be introduced into S-102 when ready.

=== Check Description Format

==== Specification of validation checks

Individual checks are defined in the format described in <<tab-check-specification-format>>.

[[tab-check-specification-format]]
.Check specification format
[cols="a,2a",options="header"]
|===
| Column	| Description

|Data Quality Measure or Theme	| Quality measure or theme from S-97 Part C. +
If two measures are included in this column, the Comments column explains how the error should be classified.

| Check ID	| Identifier for check.

| Short Name	| Short name for the check.

| Prerequisite check(s)	| Checks which must succeed (check condition evaluates to FALSE) before this check can be executed. +
Trivial prerequisites are omitted from this column (such as requiring the presence of an attribute before using it in a condition).

| Context test (IF ...) or  initialization (SET ...)	| Combination of test conditions and initialization statements. +
Test conditions check for the existence of an GML attribute, group, or other element (for example, #TBD#), the value of a metadata attribute, or for required conditions applicable to combinations of attributes (for example, checking that cell size, numbers of rows and columns, and the geographical extent of the grid are mutually consistent). +
Initialization statements set the value of parameters used in the specific test in that row. +
The scope of the test condition or initialization is limited to the check described in that row.
| Check condition description	| Specification of check condition, written in structured English. +
The conditions are written so that if the condition evaluates to TRUE it indicates an error or other issue exists in the dataset.

| Check message	| Message to emit if dataset fails the check condition (condition evaluates to TRUE). +
Implementers should include the location where the error is encountered (for example, the name and path from the root group).

| Check solution	| Solution to be applied to correct the failure.

| Classification	| Whether check failure is a Critical, Error, or Warning issue. See <<tab-check-classification>>.

| Post-condition	| Action to be executed if the check condition evaluates to TRUE (that is, if the check fails). +
This action will generally either set a global flag to control check processing (for example, “SET TERMINATE=TRUE”) or set a variable in the processing context which is used in later checks (for example, set a context variable to store the value of the metadata attribute dataCodingFormat).

| S-100 reference	| Reference to place in S-100 where more information about the check can be found, for example lists of allowed values for enumerations. All S-100 references for checks conforming to this Edition of S-412 are to S-100 Edition 5.2.0.

| S-102 reference	| Reference to place in S-412 where more information about the check can be found, for example allowed values for attributes of enumeration types.

| Comments	| Explanatory remarks or additional notes.

|===

==== Phase initialization

Certain parameters need to be initialized before processing of the phase begins. The required initialization statements are indicated in a sub-head row at the beginning of each phase.

==== List of checks

The individual checks are given in a spreadsheet file accompanying this Product Specification. The checks are a part of this Product Specification.

Comparisons of names in the GML dataset, exchange catalogue, and exchange set (features, attributes, GML datasets, etc.) to the Product Specification and feature catalogue should be case-sensitive.

Additional "S-100 level" checks will be defined in a separate document (under preparation by the S-100 WG). 
#NOTE S-100 GML generic checks will probablyha ot be included in this Annex.#





